backend:
    name: github
    repo: Pedr0x/blog11
    branch: main
    preview_context: my-provider/deployment
media_folder: "uploads" # Media files will be stored in the repo under images/uploads
collections:
    - name: "landingText"
      label: "Landing data"
      slug: "{{slug}}"
      create: false
      extension: "json"
      editor:
          preview: false
      files:
          - file: "_data/landingData.json"
            label: "Landing text"
            name: "landingText"
            fields:
                - { name: mainBannerText, label: "Main Banner Text", widget: "text" }
                - { name: sideContent, label: "Side text", widget: "text" }

    - name: "about"
      folder: "about"
      label: "About"
      create: false
      slug: "{{slug}}"
      fields: # The fields for each document, usually in front matter
          - { label: "Content", name: "body", widget: "markdown" }

    - name: "colors"
      label: "Colors"
      slug: "{{slug}}"
      extension: "json"
      editor:
          preview: false
      files:
          - file: "_data/cssColors.json"
            label: "Light colors theme"
            name: "cssColors"
            fields:
                - { name: primary, label: "Primary", widget: "color" }
                - { name: secondary, label: "Secondary", widget: "color" }
                - { name: tertiary, label: "tertiary", widget: "color" }
                - { name: quart, label: "quart", widget: "color" }
                - { name: quin, label: "quin", widget: "color" }
                - { name: light-text, label: "light-text", widget: "color" }
                - { name: background, label: "Background", widget: "color" }
                - { name: accent, label: "Accent", widget: "color" }
                - { name: visited-link, label: "visited-link", widget: "color" }
                - { name: invalid, label: "Invalid", widget: "color" }

    - name: "blog" # Used in routes, e.g., /admin/collections/blog
      label: "Blog" # Used in the UI
      folder: "posts-2019" # The path to the folder where the documents are stored
      create: true # Allow users to create new documents in this collection
      slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
      fields: # The fields for each document, usually in front matter
          - {
                label: "Layout",
                name: "layout",
                widget: "hidden",
                default: blogJavaScript.11ty.js,
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Content", name: "body", widget: "markdown" }
          - { label: "Landing text", name: "landingText", widget: "text" }
          - {
                label: "Main Image",
                name: "mainImage",
                widget: "file",
                default: "../../uploads/idk.jpg",
                media_library: { config: { multiple: false } },
            }
